name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  Project_name: RichardPoesBlog
  Release_folder: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Publish RPG
      run: dotnet publish $Project_name/$Project_name.csproj -c Release -o $Release_folder

    # copy index.html to 404.html to serve the same file when a file is not found
    - name: Create 404.html
      run: cp $Release_folder/wwwroot/index.html $Release_folder/wwwroot/404.html

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: ${{ env.Release_folder}}/wwwroot
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4.0.5
            